language: cpp
compiler: gcc

os:
  - linux
  # - osx

env:
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

before_install:
  # Linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y git-core make cmake gcc g++ libmad0-dev libid3tag0-dev libsndfile1-dev libgd2-xpm-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev; fi
  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew reinstall cmake libmad libid3tag libsndfile gd; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew reinstall boost --with-c++11; fi
  # Common
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar xzf release-1.8.0.tar.gz
  - ln -s googletest-release-1.8.0/googletest googletest
  - ln -s googletest-release-1.8.0/googlemock googlemock

before_script:
  - mkdir build && cd build
  - cmake -D CMAKE_BUILD_TYPE=$BUILD_TYPE ..

script:
  - make
  - ./audiowaveform_tests
