# builder image to build the audiowaveform Debian package
FROM debian:bookworm

# Use docker build --build-arg AUDIOWAVEFORM_VERSION=<git-revision> AUDIOWAVEFORM_PACKAGE_VERSION=<version>
ARG AUDIOWAVEFORM_VERSION
ENV AUDIOWAVEFORM_VERSION=${AUDIOWAVEFORM_VERSION}

ARG AUDIOWAVEFORM_PACKAGE_VERSION
ENV AUDIOWAVEFORM_PACKAGE_VERSION=${AUDIOWAVEFORM_PACKAGE_VERSION}

RUN apt-get update -y && \
    apt-get install -y wget git make cmake gcc g++ libmad0-dev \
    libid3tag0-dev libsndfile1-dev libgd-dev libboost-filesystem-dev \
    libboost-program-options-dev \
    libboost-regex-dev

# Retrieve and build source (see https://github.com/bbc/audiowaveform#building-from-source)
WORKDIR /usr/local/src

RUN wget -qO- https://github.com/bbc/audiowaveform/archive/${AUDIOWAVEFORM_VERSION}.tar.gz | tar xfz - && \
    cd audiowaveform-${AUDIOWAVEFORM_VERSION} && \
    mkdir build && \
    cd build && \
    cmake -D ENABLE_TESTS=0 .. && \
    make && \
    cpack -G DEB

WORKDIR /usr/local/src/audiowaveform-${AUDIOWAVEFORM_VERSION}/build

RUN mv audiowaveform_${AUDIOWAVEFORM_PACKAGE_VERSION}-1_amd64.deb audiowaveform_${AUDIOWAVEFORM_PACKAGE_VERSION}-1-12_amd64.deb
